name: NextGenCrypto
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  http: ^0.12.2
  flutter_spinkit: ^4.1.2
  horizontal_data_table: ^2.0.0
  rflutter_alert: ^1.1.0
  flutter_glow: ^0.1.2
  intl: ^0.16.1
  fl_chart: ^0.12.2
  flutter_launcher_icons: ^0.8.1
  font_awesome_flutter: ^8.11.0
  async_loader: ^0.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/bitcoin.png"

flutter:
  uses-material-design: true

  assets:
  - images/

  fonts:
  - family: Spartan MB
    fonts:
    - asset: fonts/SpartanMB-Black.otf
      weight: 900
  - family: LibreBaskerville-Regular
    fonts :
    - asset: fonts/LibreBaskerville-Regular.ttf